-- youB — Bee Action Authorization + Impact Model V1 structural suite
-- Disposable staging only. Transactional fixtures, fail-fast assertions, no migration execution.
begin;
create temp table ctx(key text primary key, value uuid not null) on commit drop;
do $$ declare k text; begin
  foreach k in array array['bee_action_requests','intelligence_outcome_evidence'] loop
    if to_regclass('public.'||k) is null then raise exception 'missing Bee/Impact prerequisite: %', k; end if;
  end loop;
  if (select count(*) from auth.users) < 5 then raise exception 'suite requires five auth users'; end if;
end $$;
insert into ctx values
 ('org_a','11111111-1111-1111-1111-111111111111'),('org_b','22222222-2222-2222-2222-222222222222'),
 ('employee_a','11111111-0000-0000-0000-000000000001'),('employee_b','22222222-0000-0000-0000-000000000001'),
 ('recommendation_a','11111111-0000-0000-0000-000000000010'),('intervention_a','11111111-0000-0000-0000-000000000011'),
 ('action_a','11111111-0000-0000-0000-000000000012'),('outcome_a','11111111-0000-0000-0000-000000000013'),
 ('signal_a','11111111-0000-0000-0000-000000000014'),('evidence_a','11111111-0000-0000-0000-000000000015'),('evidence_contradicts','11111111-0000-0000-0000-000000000016'),
 ('bee_private','11111111-0000-0000-0000-000000000020'),('bee_other','11111111-0000-0000-0000-000000000021');
insert into ctx select 'user_'||row_number() over(order by created_at),id from auth.users order by created_at limit 5;
insert into public.organizations(id,name,slug,plan,status) values ((select value from ctx where key='org_a'),'Bee Impact A','bee-impact-a','essencial','active'),((select value from ctx where key='org_b'),'Bee Impact B','bee-impact-b','essencial','active');
insert into public.memberships(organization_id,user_id,role) values ((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'admin_youb'),((select value from ctx where key='org_a'),(select value from ctx where key='user_2'),'diretoria'),((select value from ctx where key='org_a'),(select value from ctx where key='user_3'),'gestor'),((select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'colaborador'),((select value from ctx where key='org_a'),(select value from ctx where key='user_5'),'rh');
insert into public.employees(id,organization_id,auth_user_id,full_name,email,manager_employee_id) values ((select value from ctx where key='employee_a'),(select value from ctx where key='org_a'),null,'Bee Employee A','bee-a@example.invalid',null),((select value from ctx where key='employee_b'),(select value from ctx where key='org_b'),null,'Bee Employee B','bee-b@example.invalid',null);
insert into public.intelligence_signals(id,organization_id,employee_id,signal_type,source_type) values ((select value from ctx where key='signal_a'),(select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'fixture','test');
insert into public.intelligence_evidence(id,organization_id,signal_id,evidence_type,summary,relation,independence_group,source_type) values ((select value from ctx where key='evidence_a'),(select value from ctx where key='org_a'),(select value from ctx where key='signal_a'),'documented','fixture','supports','bee-source','test'),((select value from ctx where key='evidence_contradicts'),(select value from ctx where key='org_a'),(select value from ctx where key='signal_a'),'qualitative','contradictory fixture','contradicts','independent-source','test');
insert into public.intelligence_recommendations(id,organization_id,employee_id,title) values ((select value from ctx where key='recommendation_a'),(select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'Bee fixture recommendation');
insert into public.intelligence_interventions(id,organization_id,recommendation_id,employee_id,intervention_type,title) values ((select value from ctx where key='intervention_a'),(select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='employee_a'),'fixture','Bee fixture intervention');
insert into public.intelligence_actions(id,organization_id,intervention_id,action_type,title,assignee_employee_id) values ((select value from ctx where key='action_a'),(select value from ctx where key='org_a'),(select value from ctx where key='intervention_a'),'fixture','Bee fixture action',(select value from ctx where key='employee_a'));
insert into public.intelligence_outcomes(id,organization_id,intervention_id,action_id,outcome_type) values ((select value from ctx where key='outcome_a'),(select value from ctx where key='org_a'),(select value from ctx where key='intervention_a'),(select value from ctx where key='action_a'),'fixture');
insert into public.intelligence_outcome_evidence(organization_id,outcome_id,evidence_id,relation) values ((select value from ctx where key='org_a'),(select value from ctx where key='outcome_a'),(select value from ctx where key='evidence_a'),'supports'),((select value from ctx where key='org_a'),(select value from ctx where key='outcome_a'),(select value from ctx where key='evidence_contradicts'),'contradicts');
insert into public.bee_action_requests(id,organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,purpose,target_scope_type,request_payload,execution_payload,execution_result) values ((select value from ctx where key='bee_private'),(select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'private_context','explain','informational','none','not_required','Private collaborator context','employee','{}','{}','{}'),((select value from ctx where key='bee_other'),(select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'admin_context','explain','informational','none','not_required','Admin context','organization','{}','{}','{}');

create or replace function pg_temp.assert_true(label text, condition boolean) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAIL-FAST assertion: %',label; end if; end; $$;
create or replace function pg_temp.valid_bee_request(target_org uuid,target_user uuid,target_employee uuid) returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.bee_action_requests(organization_id,requester_user_id,requester_employee_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type,target_scope_ref,target_employee_id,sensitivity,request_payload,execution_payload,execution_result) values(target_org,target_user,target_employee,'explain_context','explain','informational','none','Explain an authorized context','employee','descriptive-ref',target_employee,'standard','{}','{}','{}') returning id into probe; delete from public.bee_action_requests where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.invalid_bee_vocabularies() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'x','invalid','informational','none','x','employee');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_bee_risk() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'x','observe','invalid','none','x','employee');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.prohibited_executable() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'x','execute','prohibited_autonomous','prohibited','x','employee');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.execute_without_auth() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'x','execute','operational','none','x','employee');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_json_shape() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type,request_payload) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'x','explain','informational','none','x','employee','[]');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_bee_fk_integrity() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,requester_employee_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),(select value from ctx where key='employee_b'),'x','explain','informational','none','x','employee');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.valid_confirmation_request() returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,execution_status,confirmed_by,confirmed_at,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'confirm_action','execute','operational','confirmation','approved','ready',(select value from ctx where key='user_1'),now(),'Confirmed action','employee') returning id into probe; if (select count(*) from public.intelligence_actions where organization_id=(select value from ctx where key='org_a')) <> 1 then delete from public.bee_action_requests where id=probe;return false;end if;delete from public.bee_action_requests where id=probe;return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.valid_approval_request() returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,execution_status,approved_by,approved_at,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'approve_action','execute','sensitive','approval','approved','ready',(select value from ctx where key='user_1'),now(),'Approved action','employee') returning id into probe; if (select count(*) from public.intelligence_actions where organization_id=(select value from ctx where key='org_a')) <> 1 then delete from public.bee_action_requests where id=probe;return false;end if;delete from public.bee_action_requests where id=probe;return true;exception when others then return false;end;end;$$;
-- RLS probe is structurally valid in tenant B; no FK is intentionally broken.
create or replace function pg_temp.cross_tenant_bee_request_rls() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,requester_employee_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type,target_employee_id,request_payload,execution_payload,execution_result) values((select value from ctx where key='org_b'),(select value from ctx where key='user_1'),(select value from ctx where key='employee_b'),'tenant_b_action','explain','informational','none','Valid tenant B request','employee',(select value from ctx where key='employee_b'),'{}','{}','{}');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_outcome_level() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,outcome_level) values((select value from ctx where key='org_a'),'probe','invalid');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_claim_strength() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,claim_strength) values((select value from ctx where key='org_a'),'probe','invalid');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_impact_dates() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,window_start,window_end) values((select value from ctx where key='org_a'),'probe','2026-09-02','2026-09-01');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_financial_outcome() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,outcome_level,financial_value) values((select value from ctx where key='org_a'),'probe','financial',10);return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.invalid_causal_outcome() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,claim_strength,validation_status) values((select value from ctx where key='org_a'),'probe','causal_validated','reviewed');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.cross_tenant_outcome_evidence_integrity() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcome_evidence(organization_id,outcome_id,evidence_id,relation) values((select value from ctx where key='org_b'),(select value from ctx where key='outcome_a'),(select value from ctx where key='evidence_a'),'supports');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.probe_bee_write() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'x','explain','informational','none','x','employee');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.probe_outcome_write() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcomes(organization_id,outcome_type) values((select value from ctx where key='org_a'),'probe');return true;exception when others then return false;end;end;$$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
select pg_temp.assert_true('valid Bee vocabulary accepted',pg_temp.valid_bee_request((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),(select value from ctx where key='employee_a')));
select pg_temp.assert_true('invalid Bee capability rejected',not pg_temp.invalid_bee_vocabularies());
select pg_temp.assert_true('invalid Bee risk rejected',not pg_temp.invalid_bee_risk());
select pg_temp.assert_true('prohibited autonomous never executable',not pg_temp.prohibited_executable());
select pg_temp.assert_true('execute requires authorization',not pg_temp.execute_without_auth());
select pg_temp.assert_true('Bee JSON objects required',not pg_temp.invalid_json_shape());
select pg_temp.assert_true('invalid Bee FK rejected as integrity',not pg_temp.invalid_bee_fk_integrity());
select pg_temp.assert_true('valid confirmation enables contract only',pg_temp.valid_confirmation_request());
select pg_temp.assert_true('valid approval enables contract only',pg_temp.valid_approval_request());
select pg_temp.assert_true('admin cross-tenant Bee request denied by RLS',not pg_temp.cross_tenant_bee_request_rls());
select pg_temp.assert_true('invalid outcome level rejected',not pg_temp.invalid_outcome_level());
select pg_temp.assert_true('invalid claim strength rejected',not pg_temp.invalid_claim_strength());
select pg_temp.assert_true('invalid impact dates rejected',not pg_temp.invalid_impact_dates());
select pg_temp.assert_true('financial outcome requires currency and methodology',not pg_temp.invalid_financial_outcome());
select pg_temp.assert_true('causal validation requires validation metadata',not pg_temp.invalid_causal_outcome());
select pg_temp.assert_true('cross-tenant outcome evidence denied as integrity',not pg_temp.cross_tenant_outcome_evidence_integrity());
select pg_temp.assert_true('contradictory evidence relation is preserved',((select count(*) from public.intelligence_outcome_evidence where organization_id=(select value from ctx where key='org_a') and outcome_id=(select value from ctx where key='outcome_a') and relation='contradicts')=1));
select pg_temp.assert_true('no Bee request creates action or intervention',((select count(*) from public.intelligence_actions where organization_id=(select value from ctx where key='org_a'))=1 and (select count(*) from public.intelligence_interventions where organization_id=(select value from ctx where key='org_a'))=1));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_5'),true);
select pg_temp.assert_true('RH reads own tenant Bee requests',((select count(*) from public.bee_action_requests where organization_id=(select value from ctx where key='org_a'))=2));
select pg_temp.assert_true('RH cross-tenant Bee request denied by RLS',not pg_temp.cross_tenant_bee_request_rls());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_2'),true);
select pg_temp.assert_true('diretoria cannot write Bee requests',not pg_temp.probe_bee_write());
select pg_temp.assert_true('diretoria can read Outcomes',((select count(*) from public.intelligence_outcomes where organization_id=(select value from ctx where key='org_a'))=1));
select pg_temp.assert_true('diretoria cannot write Outcomes',not pg_temp.probe_outcome_write());
select pg_temp.assert_true('diretoria cannot read private collaborator request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_private'))=0));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_3'),true);
select pg_temp.assert_true('gestor cannot write Bee requests',not pg_temp.probe_bee_write());
select pg_temp.assert_true('gestor cannot write Outcomes',not pg_temp.probe_outcome_write());
select pg_temp.assert_true('gestor cannot read private collaborator request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_private'))=0));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_4'),true);
select pg_temp.assert_true('collaborator cannot write Bee requests',not pg_temp.probe_bee_write());
select pg_temp.assert_true('collaborator cannot write Outcomes',not pg_temp.probe_outcome_write());
select pg_temp.assert_true('requester reads own Bee request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_private'))=1));
select pg_temp.assert_true('requester cannot read another users request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_other'))=0));
select pg_temp.assert_true('collaborator cannot read generic request list',((select count(*) from public.bee_action_requests)=1));
-- JSON is diagnostic only; all critical conditions above are authoritative fail-fast assertions.
rollback;
