-- youB — Intelligence Core authenticated role/cross-tenant suite
-- Disposable staging only. This suite never applies migrations and rolls back all fixtures.
begin;
create temp table suite_context(key text primary key, value uuid not null) on commit drop;
do $$ declare t text; begin foreach t in array array['intelligence_signals','intelligence_evidence','intelligence_recommendations','intelligence_interventions','intelligence_actions','intelligence_outcomes','intelligence_recommendation_evidence','knowledge_sources','knowledge_documents'] loop if to_regclass('public.'||t) is null then raise exception 'missing intelligence prerequisite: %', t; end if; end loop; if (select count(*) from auth.users) < 4 then raise exception 'suite requires four auth users'; end if; end $$;
insert into suite_context values ('org_a','cccccccc-cccc-cccc-cccc-cccccccccccc'),('org_b','dddddddd-dddd-dddd-dddd-dddddddddddd'),('employee_a','cccccccc-0000-0000-0000-000000000001'),('employee_b','dddddddd-0000-0000-0000-000000000001'),('manager_a','cccccccc-0000-0000-0000-000000000002'),('signal_a','cccccccc-0000-0000-0000-000000000003'),('evidence_a','cccccccc-0000-0000-0000-000000000004'),('recommendation_a','cccccccc-0000-0000-0000-000000000005'),('intervention_a','cccccccc-0000-0000-0000-000000000006'),('action_a','cccccccc-0000-0000-0000-000000000007'),('outcome_a','cccccccc-0000-0000-0000-000000000008'),('source_a','cccccccc-0000-0000-0000-000000000009'),('doc_org','cccccccc-0000-0000-0000-00000000000a'),('doc_management','cccccccc-0000-0000-0000-00000000000b'),('doc_restricted','cccccccc-0000-0000-0000-00000000000c');
insert into suite_context select 'user_'||row_number() over (order by created_at), id from auth.users order by created_at limit 4;
insert into public.organizations(id,name,slug,plan,status) values ((select value from suite_context where key='org_a'),'Intelligence A','intelligence-a','essencial','active'),((select value from suite_context where key='org_b'),'Intelligence B','intelligence-b','essencial','active');
insert into public.memberships(organization_id,user_id,role) values ((select value from suite_context where key='org_a'),(select value from suite_context where key='user_1'),'admin_youb'),((select value from suite_context where key='org_a'),(select value from suite_context where key='user_2'),'diretoria'),((select value from suite_context where key='org_a'),(select value from suite_context where key='user_3'),'gestor'),((select value from suite_context where key='org_a'),(select value from suite_context where key='user_4'),'colaborador');
insert into public.employees(id,organization_id,auth_user_id,full_name,email,manager_employee_id) values ((select value from suite_context where key='employee_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='user_4'),'Employee A','a@example.invalid',(select value from suite_context where key='manager_a')),((select value from suite_context where key='manager_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='user_3'),'Manager A','m@example.invalid',null),((select value from suite_context where key='employee_b'),(select value from suite_context where key='org_b'),null,'Employee B','b@example.invalid',null);
insert into public.intelligence_signals(id,organization_id,employee_id,signal_type,value,source_type) values ((select value from suite_context where key='signal_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='employee_a'),'checkin','{}','fixture');
insert into public.intelligence_evidence(id,organization_id,signal_id,evidence_type,summary,payload,source_type) values ((select value from suite_context where key='evidence_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='signal_a'),'record','fixture','{}','fixture');
insert into public.intelligence_recommendations(id,organization_id,employee_id,title) values ((select value from suite_context where key='recommendation_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='employee_a'),'Fixture recommendation');
insert into public.intelligence_interventions(id,organization_id,recommendation_id,employee_id,intervention_type,title) values ((select value from suite_context where key='intervention_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='recommendation_a'),(select value from suite_context where key='employee_a'),'fixture','Fixture intervention');
insert into public.intelligence_actions(id,organization_id,intervention_id,action_type,title,assignee_employee_id) values ((select value from suite_context where key='action_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='intervention_a'),'fixture','Fixture action',(select value from suite_context where key='employee_a'));
insert into public.intelligence_outcomes(id,organization_id,intervention_id,action_id,outcome_type,details) values ((select value from suite_context where key='outcome_a'),(select value from suite_context where key='org_a'),(select value from suite_context where key='intervention_a'),(select value from suite_context where key='action_a'),'fixture','{}');
insert into public.knowledge_sources(id,organization_id,source_type,name,access_level) values ((select value from suite_context where key='source_a'),(select value from suite_context where key='org_a'),'policy','Fixture source','organization');
insert into public.knowledge_documents(id,organization_id,knowledge_source_id,document_type,title,access_level,status) values ((select value from suite_context where key='doc_org'),(select value from suite_context where key='org_a'),(select value from suite_context where key='source_a'),'policy','Organization document','organization','published'),((select value from suite_context where key='doc_management'),(select value from suite_context where key='org_a'),(select value from suite_context where key='source_a'),'policy','Management document','management','published'),((select value from suite_context where key='doc_restricted'),(select value from suite_context where key='org_a'),(select value from suite_context where key='source_a'),'policy','Restricted document','restricted','published');
insert into public.intelligence_recommendation_evidence(organization_id,recommendation_id,evidence_id) values ((select value from suite_context where key='org_a'),(select value from suite_context where key='recommendation_a'),(select value from suite_context where key='evidence_a'));
create or replace function pg_temp.try_cross_tenant_signal() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_signals(organization_id,employee_id,signal_type,source_type) values ((select value from suite_context where key='org_a'),(select value from suite_context where key='employee_b'),'cross','test'); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.try_collaborator_insert(kind text) returns boolean language plpgsql security invoker as $$ begin begin if kind='recommendation' then insert into public.intelligence_recommendations(organization_id,employee_id,title) values ((select value from suite_context where key='org_a'),(select value from suite_context where key='employee_a'),'unauthorized'); elsif kind='evidence' then insert into public.intelligence_evidence(organization_id,signal_id,evidence_type,summary,source_type) values ((select value from suite_context where key='org_a'),(select value from suite_context where key='signal_a'),'unauthorized','unauthorized','test'); elsif kind='intervention' then insert into public.intelligence_interventions(organization_id,employee_id,intervention_type,title) values ((select value from suite_context where key='org_a'),(select value from suite_context where key='employee_a'),'unauthorized','unauthorized'); else insert into public.intelligence_outcomes(organization_id,outcome_type) values ((select value from suite_context where key='org_a'),'unauthorized'); end if; return true; exception when others then return false; end; end; $$;
select set_config('request.jwt.claim.sub',(select value::text from suite_context where key='user_4'),false); set local role authenticated;
select jsonb_build_object('cross_tenant_fk_denied',not pg_temp.try_cross_tenant_signal(),'collaborator_recommendation_insert_denied',not pg_temp.try_collaborator_insert('recommendation'),'collaborator_evidence_insert_denied',not pg_temp.try_collaborator_insert('evidence'),'collaborator_intervention_insert_denied',not pg_temp.try_collaborator_insert('intervention'),'collaborator_outcome_insert_denied',not pg_temp.try_collaborator_insert('outcome'),'organization_document_visible',(select count(*)=1 from public.knowledge_documents where access_level='organization'),'management_document_hidden',(select count(*)=0 from public.knowledge_documents where access_level='management'),'restricted_document_hidden',(select count(*)=0 from public.knowledge_documents where access_level='restricted')) as intelligence_rls_result;
reset role; rollback;

