import { CalendarDays, CheckCircle2, ClipboardList, Goal, HeartPulse, Sparkles, Target, TrendingUp } from "lucide-react";
import BeeShell, { type BeeContext } from "./BeeShell";

export type EmployeeHomeContext = { displayName: string; organizationName: string; beeContext: BeeContext };
type Card = { label: string; detail: string; icon: typeof Target };
const cards: Card[] = [
  { label: "Tarefas de hoje", detail: "Nenhuma fonte de tarefas está conectada.", icon: CheckCircle2 },
  { label: "Meu PDI", detail: "Nenhum objetivo disponível neste momento.", icon: Target },
  { label: "Próximos compromissos", detail: "Nenhum compromisso carregado.", icon: CalendarDays },
  { label: "Meu desenvolvimento", detail: "Nenhum dado de desenvolvimento disponível.", icon: TrendingUp },
];
function HomeCard({ card }: { card: Card }) { const Icon = card.icon; return <article className="rounded-3xl border border-border bg-card p-5 text-card-foreground shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{card.label}</p><div className="rounded-2xl bg-muted p-2.5 text-muted-foreground"><Icon size={19} /></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{card.detail}</p></article>; }
export default function EmployeeHome({ context }: { context: EmployeeHomeContext }) { return <main className="min-h-screen bg-background px-5 py-8 text-foreground sm:px-8"><div className="mx-auto max-w-6xl space-y-8"><header className="flex flex-col gap-5 rounded-[2rem] bg-primary p-7 text-primary-foreground shadow-lg sm:flex-row sm:items-end sm:justify-between sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-foreground/70">Minha jornada · {context.organizationName}</p><h1 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Olá, {context.displayName}</h1><p className="mt-3 max-w-xl text-sm leading-7 text-primary-foreground/80">Um espaço para acompanhar seus próximos passos com clareza e no seu ritmo.</p></div><BeeShell context={context.beeContext} /></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card) => <HomeCard key={card.label} card={card} />)}</section><section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><article className="rounded-3xl border border-border bg-card p-6 text-card-foreground shadow-sm"><div className="flex items-center gap-3"><div className="rounded-2xl bg-muted p-2.5 text-muted-foreground"><HeartPulse size={20} /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">Check-in de hoje</p><h2 className="mt-1 text-xl font-bold">Como você está?</h2></div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">O check-in estará disponível quando esta fonte for conectada. Nenhuma resposta foi registrada.</p><div className="mt-5 flex flex-wrap gap-2">{["Estou bem", "Mais ou menos", "Preciso de apoio"].map((option) => <button key={option} className="rounded-full border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:bg-muted">{option}</button>)}</div></article><article className="rounded-3xl border border-dashed border-border bg-card p-6 text-card-foreground"><div className="flex items-center gap-3"><div className="rounded-2xl bg-muted p-2.5 text-muted-foreground"><ClipboardList size={20} /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">Atalhos</p><h2 className="mt-1 text-xl font-bold">Espaços disponíveis</h2></div></div><div className="mt-5 space-y-3 text-sm text-muted-foreground"><p className="flex items-center gap-2"><Goal size={16} /> Definir um objetivo quando o PDI estiver conectado</p><p className="flex items-center gap-2"><Sparkles size={16} /> Conversar com a assistente</p></div></article></section></div></main>; }
export function EmployeeHomePreview() { return <EmployeeHome context={{ displayName: "Usuária de preview", organizationName: "Organização de preview", beeContext: { userName: "Usuária de preview", organizationName: "Organização de preview", role: "Colaborador", capabilities: ["read:own_profile"], employeeLinked: false, screen: "preview" } }} />; }
