import { CalendarDays, CheckCircle2, ClipboardList, Goal, HeartPulse, Sparkles, Target, TrendingUp } from "lucide-react";
import BeeShell from "./BeeShell";

type Card = { label: string; value: string; detail: string; icon: typeof Target; tone: string };
const cards: Card[] = [
  { label: "Tarefas de hoje", value: "Nenhuma pendente", detail: "Você está em dia por enquanto.", icon: CheckCircle2, tone: "text-emerald-600 bg-emerald-50" },
  { label: "Meu PDI", value: "Em construção", detail: "Seus próximos objetivos aparecerão aqui.", icon: Target, tone: "text-blue-600 bg-blue-50" },
  { label: "Próximos compromissos", value: "Sem compromissos", detail: "Nenhum evento conectado ainda.", icon: CalendarDays, tone: "text-violet-600 bg-violet-50" },
  { label: "Meu desenvolvimento", value: "Comece por um passo", detail: "Acompanhe sua evolução com segurança.", icon: TrendingUp, tone: "text-amber-600 bg-amber-50" },
];
function HomeCard({ card }: { card: Card }) { const Icon = card.icon; return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">{card.label}</p><p className="mt-3 text-lg font-bold text-slate-900">{card.value}</p></div><div className={`rounded-2xl p-2.5 ${card.tone}`}><Icon size={19} /></div></div><p className="mt-3 text-sm leading-6 text-slate-500">{card.detail}</p></article>; }
export default function EmployeeHome() { return <main className="min-h-screen bg-[#f5f8fc] px-5 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-6xl space-y-8"><header className="flex flex-col gap-5 rounded-[2rem] bg-gradient-to-br from-[#102654] via-[#1e3a6e] to-[#315da0] p-7 text-white shadow-lg sm:flex-row sm:items-end sm:justify-between sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-100/70">Minha jornada</p><h1 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Bom dia, Ana</h1><p className="mt-3 max-w-xl text-sm leading-7 text-blue-100/85">Um espaço simples para cuidar dos seus próximos passos, com clareza e no seu ritmo.</p></div><BeeShell context={{ userName: "Ana", organizationName: "Sua organização", role: "Colaborador", capabilities: ["read:own_profile", "read:own_development"], employeeLinked: true, screen: "employee-home" }} /></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card) => <HomeCard key={card.label} card={card} />)}</section><section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-2xl bg-rose-50 p-2.5 text-rose-600"><HeartPulse size={20} /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">Check-in de hoje</p><h2 className="mt-1 text-xl font-bold">Como você está?</h2></div></div><p className="mt-4 text-sm leading-6 text-slate-500">Este espaço está pronto para receber seu check-in. A resposta só será salva quando você confirmar.</p><div className="mt-5 flex flex-wrap gap-2">{["Estou bem", "Mais ou menos", "Preciso de apoio"].map((option) => <button key={option} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600 transition hover:border-blue-300 hover:bg-blue-50">{option}</button>)}</div></article><article className="rounded-3xl border border-dashed border-slate-300 bg-white/70 p-6"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue-50 p-2.5 text-blue-600"><ClipboardList size={20} /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-400">Atalhos</p><h2 className="mt-1 text-xl font-bold">Continue de onde parou</h2></div></div><div className="mt-5 space-y-3 text-sm text-slate-500"><p className="flex items-center gap-2"><Goal size={16} className="text-blue-600" /> Definir um objetivo de desenvolvimento</p><p className="flex items-center gap-2"><Sparkles size={16} className="text-blue-600" /> Conversar com a Bee</p></div></article></section></div></main>; }
export function EmployeeHomePreview() { return <EmployeeHome />; }

