-- youB — Recommendation & Intervention Model V1
-- Additive structural foundation only. No IA, scoring, ranking, matching or automatic execution.
alter table public.intelligence_recommendations add column if not exists recommendation_type text, add column if not exists scope_type text, add column if not exists scope_ref text, add column if not exists evidence_state text, add column if not exists problem_statement text, add column if not exists unknowns jsonb not null default '[]'::jsonb, add column if not exists recommended_intervention_type text, add column if not exists alternatives jsonb not null default '[]'::jsonb, add column if not exists do_not_recommend jsonb not null default '[]'::jsonb, add column if not exists expected_outcome text, add column if not exists measurement_plan jsonb not null default '{}'::jsonb, add column if not exists estimated_cost numeric, add column if not exists currency text, add column if not exists owner_employee_id uuid, add column if not exists approval_required boolean not null default false, add column if not exists approved_by uuid, add column if not exists approved_at timestamptz, add column if not exists follow_up_at timestamptz, add column if not exists context jsonb not null default '{}'::jsonb;
do $$ begin
 if not exists(select 1 from pg_constraint where conname='recommendations_type_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_type_v1_check check(recommendation_type is null or recommendation_type in('investigate','intervene','maintain','replicate','monitor','no_action')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_scope_type_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_scope_type_v1_check check(scope_type is null or scope_type in('employee','team','area','position','process','unit','organization')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_evidence_state_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_evidence_state_v1_check check(evidence_state is null or evidence_state in('insufficient','moderate','strong')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_insufficient_intervene_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_insufficient_intervene_v1_check check(evidence_state is distinct from 'insufficient' or recommendation_type is null or recommendation_type in('investigate','monitor','no_action')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_cost_currency_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_cost_currency_v1_check check((estimated_cost is null and currency is null) or(estimated_cost is not null and estimated_cost>=0 and currency is not null and length(btrim(currency))>0)); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_unknowns_array_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_unknowns_array_v1_check check(jsonb_typeof(unknowns)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_alternatives_array_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_alternatives_array_v1_check check(jsonb_typeof(alternatives)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_do_not_recommend_array_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_do_not_recommend_array_v1_check check(jsonb_typeof(do_not_recommend)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_measurement_plan_object_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_measurement_plan_object_v1_check check(jsonb_typeof(measurement_plan)='object'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_context_object_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_context_object_v1_check check(jsonb_typeof(context)='object'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_owner_same_org_fkey') then alter table public.intelligence_recommendations add constraint recommendations_owner_same_org_fkey foreign key(organization_id,owner_employee_id) references public.employees(organization_id,id); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_approved_by_fkey') then alter table public.intelligence_recommendations add constraint recommendations_approved_by_fkey foreign key(approved_by) references auth.users(id) on delete set null; end if;
end $$;
alter table public.intelligence_interventions add column if not exists intervention_family text, add column if not exists objective text, add column if not exists target_scope_type text, add column if not exists target_scope_ref text, add column if not exists success_criteria jsonb not null default '[]'::jsonb, add column if not exists measurement_plan jsonb not null default '{}'::jsonb, add column if not exists estimated_cost numeric, add column if not exists currency text, add column if not exists starts_at timestamptz, add column if not exists expected_end_at timestamptz, add column if not exists follow_up_at timestamptz, add column if not exists requires_human_approval boolean not null default false, add column if not exists context jsonb not null default '{}'::jsonb;
do $$ begin
 if not exists(select 1 from pg_constraint where conname='interventions_family_v1_check') then alter table public.intelligence_interventions add constraint interventions_family_v1_check check(intervention_family is null or intervention_family in('investigation','learning','mentoring','coaching','leadership','process','work_design','communication','recognition','career','succession','mobility','structure','people_practice','consulting','none')); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_target_scope_type_v1_check') then alter table public.intelligence_interventions add constraint interventions_target_scope_type_v1_check check(target_scope_type is null or target_scope_type in('employee','team','area','position','process','unit','organization')); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_dates_v1_check') then alter table public.intelligence_interventions add constraint interventions_dates_v1_check check(starts_at is null or expected_end_at is null or expected_end_at>=starts_at); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_cost_currency_v1_check') then alter table public.intelligence_interventions add constraint interventions_cost_currency_v1_check check((estimated_cost is null and currency is null) or(estimated_cost is not null and estimated_cost>=0 and currency is not null and length(btrim(currency))>0)); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_success_criteria_array_v1_check') then alter table public.intelligence_interventions add constraint interventions_success_criteria_array_v1_check check(jsonb_typeof(success_criteria)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_measurement_plan_object_v1_check') then alter table public.intelligence_interventions add constraint interventions_measurement_plan_object_v1_check check(jsonb_typeof(measurement_plan)='object'); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_context_object_v1_check') then alter table public.intelligence_interventions add constraint interventions_context_object_v1_check check(jsonb_typeof(context)='object'); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_recommendation_same_org_fkey') then alter table public.intelligence_interventions add constraint interventions_recommendation_same_org_fkey foreign key(organization_id,recommendation_id) references public.intelligence_recommendations(organization_id,id); end if;
end $$;
create index if not exists idx_intelligence_recommendations_org_type_state on public.intelligence_recommendations(organization_id,recommendation_type,evidence_state,status);
create index if not exists idx_intelligence_recommendations_org_scope on public.intelligence_recommendations(organization_id,scope_type);
create index if not exists idx_intelligence_interventions_org_family_scope on public.intelligence_interventions(organization_id,intervention_family,target_scope_type);
drop policy if exists intelligence_recommendations_insert_role on public.intelligence_recommendations;
drop policy if exists intelligence_recommendations_update_role on public.intelligence_recommendations;
create policy intelligence_recommendations_insert_role on public.intelligence_recommendations for insert to authenticated with check(public.intelligence_is_admin(organization_id));
create policy intelligence_recommendations_update_role on public.intelligence_recommendations for update to authenticated using(public.intelligence_is_admin(organization_id)) with check(public.intelligence_is_admin(organization_id));
drop policy if exists intelligence_interventions_insert_role on public.intelligence_interventions;
drop policy if exists intelligence_interventions_update_role on public.intelligence_interventions;
create policy intelligence_interventions_insert_role on public.intelligence_interventions for insert to authenticated with check(public.intelligence_is_admin(organization_id));
create policy intelligence_interventions_update_role on public.intelligence_interventions for update to authenticated using(public.intelligence_is_admin(organization_id)) with check(public.intelligence_is_admin(organization_id));
drop policy if exists recommendation_evidence_insert on public.intelligence_recommendation_evidence;
create policy recommendation_evidence_insert on public.intelligence_recommendation_evidence for insert to authenticated with check(public.intelligence_is_admin(organization_id));
comment on table public.intelligence_recommendations is 'Structured, explainable contract for Leitura Organizacional. No automatic generation, scoring or execution.';
comment on column public.intelligence_recommendations.scope_ref is 'Reference only; never an authorization mechanism.';
comment on column public.intelligence_recommendations.source_evidence_ids is 'Compatibility only; intelligence_recommendation_evidence is authoritative.';
comment on table public.intelligence_interventions is 'Extensible intervention contract. No recommendation-to-intervention automation or execution in V1.';
comment on column public.intelligence_interventions.target_scope_ref is 'Reference only; never an authorization mechanism.';
